/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import java.awt.Font;
import java.awt.Toolkit;
import java.util.Arrays;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import utilities.ReadexProLoader;
import classes.User;
import classes.Database;

/**
 *
 * @author William
 */
public class Login extends javax.swing.JFrame {
    Font readexPro;
    Font readexProSemiBold;
    
    public User user;

    /**
     * Creates new form UserInformationEntry
     */
    public Login() {
        setIconImage();
        setFonts();
        initComponents();
        focus();
    }
    
    public Login(String email) {
        setIconImage();
        setFonts();
        initComponents();
        setEmail(email);
        focus();
    }
    
    private void setEmail(String email) {
        txtEmail.setText(email);
        txtEmail.setForeground(new java.awt.Color(58,50,44));
    }
    
    private void focus() {
        pnlMain.requestFocus();
    }
    
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../assets/Flora_Logo_20x20.png")));
    }
    
    private void setFonts() {
        ReadexProLoader loader = new ReadexProLoader();
        
        readexPro = loader.readexPro(12);
        readexProSemiBold = loader.readexProSemiBold(32);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlHeadings = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlForms = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        pnlBtns = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flora Macatan");

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setLayout(new java.awt.BorderLayout());

        pnlHeadings.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeadings.setBorder(javax.swing.BorderFactory.createEmptyBorder(64, 192, 0, 192));
        pnlHeadings.setLayout(new java.awt.GridLayout(3, 0));

        jLabel1.setFont(readexProSemiBold);
        jLabel1.setForeground(new java.awt.Color(58, 50, 44));
        jLabel1.setText("<html><head><style>body { font-family: \"Readex Pro\"; font-weight: 700; }</style></head>Welcome <font color=\"#5B3700\">back!</font></html>");
        pnlHeadings.add(jLabel1);

        jLabel2.setFont(readexPro);
        jLabel2.setForeground(new java.awt.Color(171, 171, 171));
        jLabel2.setText("Provide your account information");
        pnlHeadings.add(jLabel2);

        jSeparator1.setForeground(new java.awt.Color(246, 246, 246));
        pnlHeadings.add(jSeparator1);

        pnlMain.add(pnlHeadings, java.awt.BorderLayout.NORTH);

        pnlForms.setBackground(new java.awt.Color(255, 255, 255));
        pnlForms.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 192, 0, 192));
        pnlForms.setLayout(new java.awt.GridLayout(2, 0, 0, 16));

        txtEmail.setBackground(new java.awt.Color(246, 246, 246));
        txtEmail.setFont(readexPro);
        txtEmail.setForeground(new java.awt.Color(171, 171, 171));
        txtEmail.setText("Email");
        txtEmail.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 201, 201), 1, true), javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16)));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        pnlForms.add(txtEmail);

        txtPassword.setBackground(new java.awt.Color(246, 246, 246));
        txtPassword.setFont(readexPro);
        txtPassword.setForeground(new java.awt.Color(171, 171, 171));
        txtPassword.setText("Password");
        txtPassword.setBorder(txtEmail.getBorder());
        txtPassword.setEchoChar('\u0000');
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        pnlForms.add(txtPassword);

        pnlMain.add(pnlForms, java.awt.BorderLayout.CENTER);

        pnlBtns.setBackground(new java.awt.Color(255, 255, 255));
        pnlBtns.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 192, 64, 192));
        pnlBtns.setLayout(new java.awt.GridLayout(1, 0, 16, 0));

        btnBack.setBackground(new java.awt.Color(246, 246, 246));
        btnBack.setFont(readexPro);
        btnBack.setForeground(new java.awt.Color(58, 50, 44));
        btnBack.setText("Back");
        btnBack.setToolTipText("");
        btnBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16));
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlBtns.add(btnBack);

        btnLogin.setBackground(new java.awt.Color(91, 55, 0));
        btnLogin.setFont(readexPro);
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16));
        btnLogin.setBorderPainted(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlBtns.add(btnLogin);

        pnlMain.add(pnlBtns, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Home().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        if (txtEmail.getText().equals("Email")) {
            txtEmail.setText("");
            txtEmail.setForeground(new java.awt.Color(58,50,44));
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if (txtEmail.getText().equals("")) {
            txtEmail.setText("Email");
            txtEmail.setForeground(new java.awt.Color(171, 171, 171));
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        if (Arrays.equals(txtPassword.getPassword(), "Password".toCharArray())) {
            txtPassword.setText("");
            txtPassword.setForeground(new java.awt.Color(58,50,44));
            txtPassword.setFont(new Font("Segoe UI", 0, 12));
            txtPassword.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if (Arrays.equals(txtPassword.getPassword(), "".toCharArray())) {
            txtPassword.setText("Password");
            txtPassword.setForeground(new java.awt.Color(171, 171, 171));
            txtPassword.setFont(readexPro);
            txtPassword.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String email = txtEmail.getText();
        String password = new String(txtPassword.getPassword());
        
        try {
            String query = "SELECT * FROM floramacatan.user WHERE email = ?";
            PreparedStatement stmt = Database.sqlConnection.prepareStatement(query);
            
            stmt.setString(1, txtEmail.getText());

            ResultSet rs = stmt.executeQuery();
            
            if (rs.next()) {
                String name = rs.getString("name");
                String address = rs.getString("address");
                String contact = rs.getString("contact");
                String userId = rs.getString("userId");
                String dbPassword = rs.getString("password");
                
                if (password.equals(dbPassword)) {
                    new User(name, address, contact, email, password, userId);
                    
                    new Dashboard().setVisible(true);
                    
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid credentials");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Invalid credentials");
            }
        } catch (SQLException e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlBtns;
    private javax.swing.JPanel pnlForms;
    private javax.swing.JPanel pnlHeadings;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
