/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import utilities.ReadexProLoader;

/**
 *
 * @author jejer
 */
public class PaymentProcessing extends javax.swing.JFrame {
    ReservationConfirmation reservationConfirmation;
    Font readexPro;
    Font readexProSemiBold;
    Font readexProTotal;
    
    /**
     * Creates new form PaymentProcessing
     */
    public PaymentProcessing() {
        setIconImage();
        setFonts();
        initComponents();
        
        btnCard.setSelected(true);
    }
    
    public PaymentProcessing(ReservationConfirmation reservationConfirmation) {
        this.reservationConfirmation = reservationConfirmation;
        
        setIconImage();
        setFonts();
        initComponents();
        
        btnCard.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaymentMethods = new javax.swing.ButtonGroup();
        CardType = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel5 = new javax.swing.JPanel();
        pnlDetails = new javax.swing.JPanel();
        pnlHeadings = new javax.swing.JPanel();
        lblRoom = new javax.swing.JLabel();
        lblRoomType = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnPayNow = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlPaymentMethod = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlPMButtons = new javax.swing.JPanel();
        btnCard = new javax.swing.JToggleButton();
        btnPaypal = new javax.swing.JToggleButton();
        btnGcash = new javax.swing.JToggleButton();
        btnMaya = new javax.swing.JToggleButton();
        pnlPayment = new javax.swing.JPanel();
        pnlCard = new javax.swing.JPanel();
        pnlCardType = new javax.swing.JPanel();
        lblCardType = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnVisa = new javax.swing.JRadioButton();
        btnMtrcd = new javax.swing.JRadioButton();
        btnAmex = new javax.swing.JRadioButton();
        lblNum = new javax.swing.JLabel();
        txtCardNum = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblNum1 = new javax.swing.JLabel();
        txtExp = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        lblNum6 = new javax.swing.JLabel();
        txtCVV = new javax.swing.JTextField();
        pnlPaypal = new javax.swing.JPanel();
        lblNum10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblNum11 = new javax.swing.JLabel();
        pwd = new javax.swing.JPasswordField();
        pnlMobile = new javax.swing.JPanel();
        lblNum12 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flora Macatan");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.BorderLayout());

        pnlDetails.setBackground(new java.awt.Color(255, 255, 255));
        pnlDetails.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        pnlDetails.setToolTipText("");
        pnlDetails.setLayout(new java.awt.BorderLayout());

        pnlHeadings.setBackground(new java.awt.Color(246, 246, 246));
        pnlHeadings.setBorder(javax.swing.BorderFactory.createEmptyBorder(56, 56, 0, 56));
        pnlHeadings.setLayout(new java.awt.GridLayout(2, 0));

        lblRoom.setFont(readexPro);
        lblRoom.setForeground(new java.awt.Color(94, 94, 94));
        lblRoom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRoom.setText("Room");
        pnlHeadings.add(lblRoom);

        lblRoomType.setFont(readexPro);
        lblRoomType.setForeground(new java.awt.Color(91, 55, 0));
        lblRoomType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRoomType.setText("Standard");
        pnlHeadings.add(lblRoomType);

        pnlDetails.add(pnlHeadings, java.awt.BorderLayout.NORTH);

        jPanel4.setBackground(new java.awt.Color(246, 246, 246));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 112, 0, 112));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(246, 246, 246));
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 64, 0, 64));
        jPanel6.setLayout(new java.awt.GridLayout(2, 0, 112, 0));

        jLabel4.setFont(readexPro);
        jLabel4.setForeground(new java.awt.Color(171, 171, 171));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Base price");
        jPanel6.add(jLabel4);

        jLabel5.setFont(readexPro);
        jLabel5.setForeground(new java.awt.Color(94, 94, 94));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("₱1500");
        jPanel6.add(jLabel5);

        jLabel9.setFont(readexPro);
        jLabel9.setForeground(new java.awt.Color(171, 171, 171));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("No. of days");
        jLabel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 32, 0));
        jPanel6.add(jLabel9);

        jLabel10.setFont(readexPro);
        jLabel10.setForeground(new java.awt.Color(94, 94, 94));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("4");
        jLabel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 32, 0));
        jPanel6.add(jLabel10);

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel9.setBackground(new java.awt.Color(246, 246, 246));
        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 64, 0, 64));
        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jLabel7.setFont(readexProTotal);
        jLabel7.setForeground(new java.awt.Color(171, 171, 171));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Total");
        jPanel9.add(jLabel7);

        jLabel8.setFont(readexProTotal);
        jLabel8.setForeground(new java.awt.Color(94, 94, 94));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("₱1500");
        jPanel9.add(jLabel8);

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 370, 70));

        jPanel7.setBackground(new java.awt.Color(246, 246, 246));
        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 64, 64, 64));
        jPanel7.setMaximumSize(new java.awt.Dimension(46, 112));
        jPanel7.setLayout(new java.awt.BorderLayout());

        btnPayNow.setBackground(new java.awt.Color(95, 55, 38));
        btnPayNow.setFont(readexPro);
        btnPayNow.setForeground(new java.awt.Color(255, 255, 255));
        btnPayNow.setText("Pay Now");
        btnPayNow.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 1, 16, 1));
        btnPayNow.setBorderPainted(false);
        btnPayNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayNowActionPerformed(evt);
            }
        });
        jPanel7.add(btnPayNow, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 370, -1));

        pnlDetails.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel5.add(pnlDetails, java.awt.BorderLayout.EAST);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(64, 64, 64, 64));
        jPanel2.setForeground(new java.awt.Color(94, 94, 94));

        jLabel2.setFont(readexProSemiBold);
        jLabel2.setForeground(new java.awt.Color(58, 50, 44));
        jLabel2.setText("<html>Finalize your<font color=\"#5b3700\"> transaction</font></html>");

        pnlPaymentMethod.setBackground(new java.awt.Color(255, 255, 255));
        pnlPaymentMethod.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(readexPro);
        jLabel1.setForeground(new java.awt.Color(125, 124, 131));
        jLabel1.setText("Choose your preferred payment method");
        jLabel1.setToolTipText("");
        jLabel1.setPreferredSize(new java.awt.Dimension(154, 20));
        jLabel1.setRequestFocusEnabled(false);
        pnlPaymentMethod.add(jLabel1, java.awt.BorderLayout.NORTH);

        pnlPMButtons.setBackground(new java.awt.Color(255, 255, 255));
        pnlPMButtons.setPreferredSize(new java.awt.Dimension(600, 55));
        pnlPMButtons.setLayout(new java.awt.GridLayout(0, 4, 10, 0));

        btnCard.setBackground(new java.awt.Color(246, 246, 246));
        PaymentMethods.add(btnCard);
        btnCard.setFont(readexPro);
        btnCard.setForeground(new java.awt.Color(58, 50, 44));
        btnCard.setText("Credit / Debit Card");
        btnCard.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 8, 0, 8));
        btnCard.setBorderPainted(false);
        btnCard.setContentAreaFilled(false);
        btnCard.setFocusPainted(false);
        btnCard.setOpaque(true);
        btnCard.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnCardStateChanged(evt);
            }
        });
        btnCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardActionPerformed(evt);
            }
        });
        pnlPMButtons.add(btnCard);

        btnPaypal.setBackground(new java.awt.Color(246, 246, 246));
        PaymentMethods.add(btnPaypal);
        btnPaypal.setFont(readexPro);
        btnPaypal.setForeground(new java.awt.Color(58, 50, 44));
        btnPaypal.setText("PayPal");
        btnPaypal.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 8, 0, 8));
        btnPaypal.setBorderPainted(false);
        btnPaypal.setContentAreaFilled(false);
        btnPaypal.setFocusPainted(false);
        btnPaypal.setOpaque(true);
        btnPaypal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnPaypalStateChanged(evt);
            }
        });
        btnPaypal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaypalActionPerformed(evt);
            }
        });
        pnlPMButtons.add(btnPaypal);

        btnGcash.setBackground(new java.awt.Color(246, 246, 246));
        PaymentMethods.add(btnGcash);
        btnGcash.setFont(readexPro);
        btnGcash.setForeground(new java.awt.Color(58, 50, 44));
        btnGcash.setText("GCash");
        btnGcash.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 8, 0, 8));
        btnGcash.setBorderPainted(false);
        btnGcash.setContentAreaFilled(false);
        btnGcash.setFocusPainted(false);
        btnGcash.setOpaque(true);
        btnGcash.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnGcashStateChanged(evt);
            }
        });
        btnGcash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGcashActionPerformed(evt);
            }
        });
        pnlPMButtons.add(btnGcash);

        btnMaya.setBackground(new java.awt.Color(246, 246, 246));
        PaymentMethods.add(btnMaya);
        btnMaya.setFont(readexPro);
        btnMaya.setForeground(new java.awt.Color(58, 50, 44));
        btnMaya.setText("Maya");
        btnMaya.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 8, 0, 8));
        btnMaya.setBorderPainted(false);
        btnMaya.setContentAreaFilled(false);
        btnMaya.setFocusPainted(false);
        btnMaya.setOpaque(true);
        btnMaya.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnMayaStateChanged(evt);
            }
        });
        btnMaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMayaActionPerformed(evt);
            }
        });
        pnlPMButtons.add(btnMaya);

        pnlPaymentMethod.add(pnlPMButtons, java.awt.BorderLayout.SOUTH);

        pnlPayment.setLayout(new java.awt.CardLayout());

        pnlCard.setBackground(new java.awt.Color(255, 255, 255));

        pnlCardType.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardType.setLayout(new java.awt.BorderLayout(0, 2));

        lblCardType.setFont(readexPro);
        lblCardType.setForeground(new java.awt.Color(125, 124, 131));
        lblCardType.setText("Select card type");
        pnlCardType.add(lblCardType, java.awt.BorderLayout.NORTH);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnVisa.setBackground(new java.awt.Color(255, 255, 255));
        CardType.add(btnVisa);
        btnVisa.setFont(readexPro);
        btnVisa.setSelected(true);
        btnVisa.setText("Visa");
        btnVisa.setFocusPainted(false);
        btnVisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnVisaFocusLost(evt);
            }
        });
        btnVisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaActionPerformed(evt);
            }
        });
        jPanel3.add(btnVisa);

        btnMtrcd.setBackground(new java.awt.Color(255, 255, 255));
        CardType.add(btnMtrcd);
        btnMtrcd.setFont(readexPro);
        btnMtrcd.setForeground(new java.awt.Color(125, 124, 131));
        btnMtrcd.setText("Mastercard");
        btnMtrcd.setFocusPainted(false);
        btnMtrcd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnMtrcdFocusLost(evt);
            }
        });
        btnMtrcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMtrcdActionPerformed(evt);
            }
        });
        jPanel3.add(btnMtrcd);

        btnAmex.setBackground(new java.awt.Color(255, 255, 255));
        CardType.add(btnAmex);
        btnAmex.setFont(readexPro);
        btnAmex.setForeground(new java.awt.Color(125, 124, 131));
        btnAmex.setText("American Express");
        btnAmex.setFocusPainted(false);
        btnAmex.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnAmexFocusLost(evt);
            }
        });
        btnAmex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmexActionPerformed(evt);
            }
        });
        jPanel3.add(btnAmex);

        pnlCardType.add(jPanel3, java.awt.BorderLayout.SOUTH);

        lblNum.setFont(readexPro);
        lblNum.setForeground(new java.awt.Color(171, 171, 171));
        lblNum.setText("Card number");

        txtCardNum.setBackground(new java.awt.Color(246, 246, 246));
        txtCardNum.setFont(readexPro);
        txtCardNum.setForeground(new java.awt.Color(125, 124, 131));
        txtCardNum.setText("xxxx xxxx xxxx xxxx");
        txtCardNum.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 201, 201), 1, true), javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8)));
        txtCardNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCardNumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCardNumFocusLost(evt);
            }
        });
        txtCardNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCardNumActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 8, 0));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.GridLayout(2, 0));

        lblNum1.setFont(readexPro);
        lblNum1.setForeground(new java.awt.Color(171, 171, 171));
        lblNum1.setText("Expiry date");
        jPanel8.add(lblNum1);

        txtExp.setBackground(new java.awt.Color(246, 246, 246));
        txtExp.setFont(readexPro);
        txtExp.setForeground(new java.awt.Color(125, 124, 131));
        txtExp.setText("mm / yy");
        txtExp.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 201, 201), 1, true), javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8)));
        txtExp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtExpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtExpFocusLost(evt);
            }
        });
        txtExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExpActionPerformed(evt);
            }
        });
        jPanel8.add(txtExp);

        jPanel1.add(jPanel8);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.GridLayout(2, 0));

        lblNum6.setFont(readexPro);
        lblNum6.setForeground(new java.awt.Color(171, 171, 171));
        lblNum6.setText("CVV");
        jPanel10.add(lblNum6);

        txtCVV.setBackground(new java.awt.Color(246, 246, 246));
        txtCVV.setFont(readexPro);
        txtCVV.setForeground(new java.awt.Color(125, 124, 131));
        txtCVV.setText("xxx");
        txtCVV.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 201, 201), 1, true), javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8)));
        txtCVV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCVVFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCVVFocusLost(evt);
            }
        });
        txtCVV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCVVActionPerformed(evt);
            }
        });
        jPanel10.add(txtCVV);

        jPanel1.add(jPanel10);

        javax.swing.GroupLayout pnlCardLayout = new javax.swing.GroupLayout(pnlCard);
        pnlCard.setLayout(pnlCardLayout);
        pnlCardLayout.setHorizontalGroup(
            pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCardLayout.createSequentialGroup()
                        .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNum)
                            .addComponent(pnlCardType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 352, Short.MAX_VALUE))
                    .addComponent(txtCardNum, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        pnlCardLayout.setVerticalGroup(
            pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlCardType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCardNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlPayment.add(pnlCard, "card2");

        pnlPaypal.setBackground(new java.awt.Color(255, 255, 255));

        lblNum10.setFont(readexPro);
        lblNum10.setForeground(new java.awt.Color(171, 171, 171));
        lblNum10.setText("Email address");

        txtEmail.setBackground(txtCVV.getBackground());
        txtEmail.setFont(readexPro);
        txtEmail.setForeground(new java.awt.Color(125, 124, 131));
        txtEmail.setText("xxxxx@xxxxxxxx.xxx");
        txtEmail.setBorder(txtCVV.getBorder());
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblNum11.setFont(readexPro);
        lblNum11.setForeground(new java.awt.Color(171, 171, 171));
        lblNum11.setText("Password");

        pwd.setBackground(txtCVV.getBackground());
        pwd.setForeground(new java.awt.Color(125, 124, 131));
        pwd.setBorder(txtCVV.getBorder());
        pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPaypalLayout = new javax.swing.GroupLayout(pnlPaypal);
        pnlPaypal.setLayout(pnlPaypalLayout);
        pnlPaypalLayout.setHorizontalGroup(
            pnlPaypalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaypalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPaypalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPaypalLayout.createSequentialGroup()
                        .addGroup(pnlPaypalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNum10)
                            .addComponent(lblNum11))
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPaypalLayout.createSequentialGroup()
                        .addGroup(pnlPaypalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pwd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        pnlPaypalLayout.setVerticalGroup(
            pnlPaypalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaypalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNum10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNum11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pnlPayment.add(pnlPaypal, "card2");

        pnlMobile.setBackground(new java.awt.Color(255, 255, 255));

        lblNum12.setFont(readexPro);
        lblNum12.setForeground(new java.awt.Color(171, 171, 171));
        lblNum12.setText("Mobile number");

        txtMobile.setBackground(txtCVV.getBackground());
        txtMobile.setFont(new java.awt.Font("Readex Pro", 0, 12)); // NOI18N
        txtMobile.setForeground(new java.awt.Color(125, 124, 131));
        txtMobile.setText("09xxxxxxxxx");
        txtMobile.setBorder(txtCardNum.getBorder());
        txtMobile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMobileFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMobileFocusLost(evt);
            }
        });
        txtMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMobileLayout = new javax.swing.GroupLayout(pnlMobile);
        pnlMobile.setLayout(pnlMobileLayout);
        pnlMobileLayout.setHorizontalGroup(
            pnlMobileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMobileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMobileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMobileLayout.createSequentialGroup()
                        .addComponent(lblNum12)
                        .addGap(222, 222, 222))
                    .addGroup(pnlMobileLayout.createSequentialGroup()
                        .addComponent(txtMobile, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnlMobileLayout.setVerticalGroup(
            pnlMobileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMobileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNum12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pnlPayment.add(pnlMobile, "card2");

        btnBack.setBackground(new java.awt.Color(246, 246, 246));
        btnBack.setFont(readexPro);
        btnBack.setForeground(new java.awt.Color(58, 50, 44));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 32, 16, 32));
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPaymentMethod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlPayment.getAccessibleContext().setAccessibleName("");

        jPanel5.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../assets/Flora_Logo_20x20.png")));
    }
    
    private void setFonts() {
        ReadexProLoader loader = new ReadexProLoader();
        
        readexPro = loader.readexPro(12);
        readexProSemiBold = loader.readexProSemiBold(18);
        readexProTotal = loader.readexPro(16);
    }
    
    private void setPaymentBtnColors() {
        if (btnCard.isSelected()) {
            btnCard.setBackground(new java.awt.Color(95, 55,38));
            btnCard.setForeground(new java.awt.Color(255, 255,255));
            
            btnPaypal.setBackground(new java.awt.Color(246, 246, 246));
            btnPaypal.setForeground(new java.awt.Color(58,50,44));
            
            btnGcash.setBackground(new java.awt.Color(246, 246, 246));
            btnGcash.setForeground(new java.awt.Color(58,50,44));
            
            btnMaya.setBackground(new java.awt.Color(246, 246, 246));
            btnMaya.setForeground(new java.awt.Color(58,50,44));
        } else if (btnPaypal.isSelected()) {
            btnPaypal.setBackground(new java.awt.Color(95, 55,38));
            btnPaypal.setForeground(new java.awt.Color(255, 255,255));
            
            btnCard.setBackground(new java.awt.Color(246, 246, 246));
            btnCard.setForeground(new java.awt.Color(58,50,44));
            
            btnGcash.setBackground(new java.awt.Color(246, 246, 246));
            btnGcash.setForeground(new java.awt.Color(58,50,44));
            
            btnMaya.setBackground(new java.awt.Color(246, 246, 246));
            btnMaya.setForeground(new java.awt.Color(58,50,44));
        } else if (btnGcash.isSelected()) {
            btnGcash.setBackground(new java.awt.Color(95, 55,38));
            btnGcash.setForeground(new java.awt.Color(255, 255,255));
            
            btnCard.setBackground(new java.awt.Color(246, 246, 246));
            btnCard.setForeground(new java.awt.Color(58,50,44));
            
            btnPaypal.setBackground(new java.awt.Color(246, 246, 246));
            btnPaypal.setForeground(new java.awt.Color(58,50,44));
            
            btnMaya.setBackground(new java.awt.Color(246, 246, 246));
            btnMaya.setForeground(new java.awt.Color(58,50,44));
        } else if (btnMaya.isSelected()) {
            btnMaya.setBackground(new java.awt.Color(95, 55,38));
            btnMaya.setForeground(new java.awt.Color(255, 255,255));
            
            btnCard.setBackground(new java.awt.Color(246, 246, 246));
            btnCard.setForeground(new java.awt.Color(58,50,44));
            
            btnPaypal.setBackground(new java.awt.Color(246, 246, 246));
            btnPaypal.setForeground(new java.awt.Color(58,50,44));
            
            btnGcash.setBackground(new java.awt.Color(246, 246, 246));
            btnGcash.setForeground(new java.awt.Color(58,50,44));
        }
    }
    
    private void btnGcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGcashActionPerformed
        pnlPayment.removeAll();
        pnlPayment.add(pnlMobile);
        pnlPayment.repaint();
        pnlPayment.revalidate();
        
        
    }//GEN-LAST:event_btnGcashActionPerformed

    private void btnMayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayaActionPerformed
        pnlPayment.removeAll();
        pnlPayment.add(pnlMobile);
        pnlPayment.repaint();
        pnlPayment.revalidate();
    }//GEN-LAST:event_btnMayaActionPerformed

    private void btnPaypalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaypalActionPerformed
        pnlPayment.removeAll();
        pnlPayment.add(pnlPaypal);
        pnlPayment.repaint();
        pnlPayment.revalidate();
    }//GEN-LAST:event_btnPaypalActionPerformed

    private void btnVisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaActionPerformed
        btnVisa.setForeground(Color.black);
    }//GEN-LAST:event_btnVisaActionPerformed

    private void btnMtrcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMtrcdActionPerformed
        btnMtrcd.setForeground(Color.black);
        btnVisa.setForeground(new java.awt.Color(125, 124, 131));
    }//GEN-LAST:event_btnMtrcdActionPerformed

    private void btnAmexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmexActionPerformed
        btnAmex.setForeground(Color.black);
        btnVisa.setForeground(new java.awt.Color(125, 124, 131));
    }//GEN-LAST:event_btnAmexActionPerformed

    private void txtCardNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCardNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCardNumActionPerformed

    private void txtExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExpActionPerformed

    private void txtCVVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCVVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCVVActionPerformed

    private void txtCardNumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCardNumFocusGained
        if ("xxxx xxxx xxxx xxxx".equals(txtCardNum.getText())) {
            txtCardNum.setText("");
            txtCardNum.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCardNumFocusGained

    private void txtExpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtExpFocusGained
        if ("mm / yy".equals(txtExp.getText())) {
            txtExp.setText("");
            txtExp.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtExpFocusGained

    private void txtCVVFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCVVFocusGained
        if ("xxx".equals(txtCVV.getText())) {
            txtCVV.setText("");
            txtCVV.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCVVFocusGained

    private void txtCardNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCardNumFocusLost
        if ("".equals(txtCardNum.getText())) {
            txtCardNum.setText("xxxx xxxx xxxx xxxx");
            txtCardNum.setForeground(new java.awt.Color(125, 124, 131));
        }
    }//GEN-LAST:event_txtCardNumFocusLost

    private void txtExpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtExpFocusLost
        if ("".equals(txtExp.getText())) {
            txtExp.setText("mm / yy");
            txtExp.setForeground(new java.awt.Color(125, 124, 131));
        }
    }//GEN-LAST:event_txtExpFocusLost

    private void txtCVVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCVVFocusLost
        if ("".equals(txtCVV.getText())) {
            txtCVV.setText("xxx");
            txtCVV.setForeground(new java.awt.Color(125, 124, 131));
        }
    }//GEN-LAST:event_txtCVVFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        if ("xxxxx@xxxxxxxx.xxx".equals(txtEmail.getText())) {
            txtEmail.setText("");
            txtEmail.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if ("".equals(txtEmail.getText())) {
            txtEmail.setText("xxxxx@xxxxxxxx.xxx");
            txtEmail.setForeground(new java.awt.Color(125, 124, 131));
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtMobileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMobileFocusGained
        if ("09xxxxxxxxx".equals(txtMobile.getText())) {
            txtMobile.setText("09");
            txtMobile.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtMobileFocusGained

    private void txtMobileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMobileFocusLost
        if ("".equals(txtMobile.getText()) || "09".equals(txtMobile.getText())) {
            txtMobile.setText("09xxxxxxxxx");
            txtMobile.setForeground(new java.awt.Color(125, 124, 131));
        }
    }//GEN-LAST:event_txtMobileFocusLost

    private void txtMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdActionPerformed

    private void btnVisaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnVisaFocusLost
        btnVisa.setForeground(new java.awt.Color(125, 124, 131));
    }//GEN-LAST:event_btnVisaFocusLost

    private void btnMtrcdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnMtrcdFocusLost
        btnMtrcd.setForeground(new java.awt.Color(125, 124, 131));
    }//GEN-LAST:event_btnMtrcdFocusLost

    private void btnAmexFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnAmexFocusLost
        btnAmex.setForeground(new java.awt.Color(125, 124, 131));
    }//GEN-LAST:event_btnAmexFocusLost

    private void btnCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardActionPerformed
        pnlPayment.removeAll();
        pnlPayment.add(pnlCard);
        pnlPayment.repaint();
        pnlPayment.revalidate();
    }//GEN-LAST:event_btnCardActionPerformed

    private void btnCardStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnCardStateChanged
        setPaymentBtnColors();
    }//GEN-LAST:event_btnCardStateChanged

    private void btnPaypalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnPaypalStateChanged
        setPaymentBtnColors();
    }//GEN-LAST:event_btnPaypalStateChanged

    private void btnGcashStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnGcashStateChanged
        setPaymentBtnColors();
    }//GEN-LAST:event_btnGcashStateChanged

    private void btnMayaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnMayaStateChanged
        setPaymentBtnColors();
    }//GEN-LAST:event_btnMayaStateChanged

    private void btnPayNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayNowActionPerformed
        new PaymentConfirmation().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnPayNowActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.reservationConfirmation.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentProcessing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentProcessing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentProcessing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentProcessing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            System.out.println("UIManager Exception : " + e);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentProcessing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup CardType;
    private javax.swing.ButtonGroup PaymentMethods;
    private javax.swing.JRadioButton btnAmex;
    private javax.swing.JButton btnBack;
    private javax.swing.JToggleButton btnCard;
    private javax.swing.JToggleButton btnGcash;
    private javax.swing.JToggleButton btnMaya;
    private javax.swing.JRadioButton btnMtrcd;
    private javax.swing.JButton btnPayNow;
    private javax.swing.JToggleButton btnPaypal;
    private javax.swing.JRadioButton btnVisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel lblCardType;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblNum1;
    private javax.swing.JLabel lblNum10;
    private javax.swing.JLabel lblNum11;
    private javax.swing.JLabel lblNum12;
    private javax.swing.JLabel lblNum6;
    private javax.swing.JLabel lblRoom;
    private javax.swing.JLabel lblRoomType;
    private javax.swing.JPanel pnlCard;
    private javax.swing.JPanel pnlCardType;
    private javax.swing.JPanel pnlDetails;
    private javax.swing.JPanel pnlHeadings;
    private javax.swing.JPanel pnlMobile;
    private javax.swing.JPanel pnlPMButtons;
    private javax.swing.JPanel pnlPayment;
    private javax.swing.JPanel pnlPaymentMethod;
    private javax.swing.JPanel pnlPaypal;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JTextField txtCVV;
    private javax.swing.JTextField txtCardNum;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtExp;
    private javax.swing.JTextField txtMobile;
    // End of variables declaration//GEN-END:variables
}
