/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import java.awt.Font;
import java.awt.Toolkit;
import utilities.ReadexProLoader;
import classes.User;
import classes.Reservation;
import java.text.SimpleDateFormat;
import java.util.Random;

/**
 *
 * @author William
 */
public class ReservationConfirmation extends javax.swing.JFrame {
    DateSelection dateSelection;
    Font readexPro;
    Font readexProSemiBold;

    /**
     * Creates new form Confirmation
     */
    public ReservationConfirmation() {
        setIconImage();
        setFonts();
        initComponents();
    }
    
    public ReservationConfirmation(DateSelection dateSelection) {
        this.dateSelection = dateSelection;
        
        setIconImage();
        setFonts();
        initComponents();
        populateData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlHeadings = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlDetails = new javax.swing.JPanel();
        pnlName = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        pnlConNo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblConNo = new javax.swing.JLabel();
        pnlEmail = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        pnlRoom = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblRoomType = new javax.swing.JLabel();
        pnlDate = new javax.swing.JPanel();
        pnlCheckIn = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblCheckIn = new javax.swing.JLabel();
        pnlCheckOut = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblCheckOut = new javax.swing.JLabel();
        pnlFooter = new javax.swing.JPanel();
        pnlPrice = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        pnlBtns = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flora Macatan");

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(64, 192, 64, 192));
        pnlMain.setLayout(new java.awt.BorderLayout());

        pnlHeadings.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeadings.setLayout(new java.awt.GridLayout(3, 0));

        jLabel1.setFont(readexProSemiBold);
        jLabel1.setForeground(new java.awt.Color(58, 50, 44));
        jLabel1.setText("<html><head><style>body { font-family: \"Readex Pro\"; font-weight: 700; }</style></head>Booking <font color=\"#5B3700\">confirmation</font</html>");
        pnlHeadings.add(jLabel1);

        jLabel2.setFont(readexPro);
        jLabel2.setForeground(new java.awt.Color(171, 171, 171));
        jLabel2.setText("Review your booking details.");
        pnlHeadings.add(jLabel2);

        jSeparator1.setForeground(new java.awt.Color(246, 246, 246));
        pnlHeadings.add(jSeparator1);

        pnlMain.add(pnlHeadings, java.awt.BorderLayout.PAGE_START);

        pnlDetails.setBackground(new java.awt.Color(255, 255, 255));
        pnlDetails.setLayout(new java.awt.GridLayout(5, 0));

        pnlName.setBackground(new java.awt.Color(255, 255, 255));
        pnlName.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setFont(readexPro);
        jLabel3.setForeground(new java.awt.Color(171, 171, 171));
        jLabel3.setText("Name:");
        pnlName.add(jLabel3);

        lblName.setFont(readexPro);
        lblName.setForeground(new java.awt.Color(58, 50, 44));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("Lore Una");
        pnlName.add(lblName);

        pnlDetails.add(pnlName);

        pnlConNo.setBackground(new java.awt.Color(255, 255, 255));
        pnlConNo.setLayout(new java.awt.GridLayout(1, 0));

        jLabel4.setFont(readexPro);
        jLabel4.setForeground(new java.awt.Color(171, 171, 171));
        jLabel4.setText("Contact number");
        pnlConNo.add(jLabel4);

        lblConNo.setFont(readexPro);
        lblConNo.setForeground(new java.awt.Color(58, 50, 44));
        lblConNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblConNo.setText("09564134959");
        pnlConNo.add(lblConNo);

        pnlDetails.add(pnlConNo);

        pnlEmail.setBackground(new java.awt.Color(255, 255, 255));
        pnlEmail.setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setFont(readexPro);
        jLabel5.setForeground(new java.awt.Color(171, 171, 171));
        jLabel5.setText("Email:");
        pnlEmail.add(jLabel5);

        lblEmail.setFont(readexPro);
        lblEmail.setForeground(new java.awt.Color(58, 50, 44));
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmail.setText("LoreUna@gmail.com");
        pnlEmail.add(lblEmail);

        pnlDetails.add(pnlEmail);

        pnlRoom.setBackground(new java.awt.Color(255, 255, 255));
        pnlRoom.setLayout(new java.awt.GridLayout(1, 0));

        jLabel6.setFont(readexPro);
        jLabel6.setForeground(new java.awt.Color(171, 171, 171));
        jLabel6.setText("Room:");
        pnlRoom.add(jLabel6);

        lblRoomType.setFont(readexPro);
        lblRoomType.setForeground(new java.awt.Color(58, 50, 44));
        lblRoomType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRoomType.setText("Suite Room");
        pnlRoom.add(lblRoomType);

        pnlDetails.add(pnlRoom);

        pnlDate.setBackground(new java.awt.Color(255, 255, 255));
        pnlDate.setLayout(new java.awt.GridLayout(1, 0));

        pnlCheckIn.setBackground(new java.awt.Color(255, 255, 255));
        pnlCheckIn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(readexPro);
        jLabel8.setForeground(new java.awt.Color(171, 171, 171));
        jLabel8.setText("Check in date:");
        pnlCheckIn.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblCheckIn.setFont(readexPro);
        lblCheckIn.setForeground(new java.awt.Color(58, 50, 44));
        lblCheckIn.setText("April 5, 2023");
        pnlCheckIn.add(lblCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        pnlDate.add(pnlCheckIn);

        pnlCheckOut.setBackground(new java.awt.Color(255, 255, 255));
        pnlCheckOut.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(readexPro);
        jLabel9.setForeground(new java.awt.Color(171, 171, 171));
        jLabel9.setText("Check out date:");
        pnlCheckOut.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblCheckOut.setFont(readexPro);
        lblCheckOut.setForeground(new java.awt.Color(58, 50, 44));
        lblCheckOut.setText("April 15, 2023");
        pnlCheckOut.add(lblCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        pnlDate.add(pnlCheckOut);

        pnlDetails.add(pnlDate);

        pnlMain.add(pnlDetails, java.awt.BorderLayout.CENTER);

        pnlFooter.setBackground(new java.awt.Color(255, 255, 255));
        pnlFooter.setBorder(javax.swing.BorderFactory.createEmptyBorder(32, 0, 0, 0));
        pnlFooter.setLayout(new java.awt.GridLayout(2, 0, 16, 0));

        pnlPrice.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrice.setLayout(new java.awt.GridLayout(1, 0));

        jLabel7.setFont(readexPro);
        jLabel7.setForeground(new java.awt.Color(171, 171, 171));
        jLabel7.setText("Total amount:");
        pnlPrice.add(jLabel7);

        lblTotal.setFont(readexPro);
        lblTotal.setForeground(new java.awt.Color(58, 50, 44));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("P8000");
        pnlPrice.add(lblTotal);

        pnlFooter.add(pnlPrice);

        pnlBtns.setBackground(new java.awt.Color(255, 255, 255));
        pnlBtns.setLayout(new java.awt.GridLayout(1, 0, 16, 0));

        btnBack.setBackground(new java.awt.Color(246, 246, 246));
        btnBack.setFont(readexPro);
        btnBack.setForeground(new java.awt.Color(58, 50, 44));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 32, 16, 32));
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlBtns.add(btnBack);

        btnPay.setBackground(new java.awt.Color(91, 55, 0));
        btnPay.setFont(readexPro);
        btnPay.setForeground(new java.awt.Color(255, 255, 255));
        btnPay.setText("Proceed to pay");
        btnPay.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 32, 16, 32));
        btnPay.setBorderPainted(false);
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });
        pnlBtns.add(btnPay);

        pnlFooter.add(pnlBtns);

        pnlMain.add(pnlFooter, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private String generateRoomNo() {
        Random random = new Random();

        char randomLetter = (char) (random.nextInt(26) + 'A');
        int randomDigit = random.nextInt(10);

        String randomString = String.valueOf(randomLetter) + randomDigit;

        return randomString;
    }
    
    private void populateData() {
        lblName.setText(User.name);
        lblConNo.setText(User.contact);
        lblEmail.setText(User.email);
        lblRoomType.setText(Reservation.roomType.substring(0,1).toUpperCase() + Reservation.roomType.substring(1).toLowerCase());
        
        int basePrice;
        String roomType = Reservation.roomType;
        
        switch (roomType) {
            case "standard":
                basePrice = 1500;
                break;
            case "connecting":
                basePrice = 2500;
                break;
            case "deluxe":
                basePrice = 4999;
                break;
            case "suite":
                basePrice = 7999;
                break;
            default:
                basePrice = 1500;
                break;
        }
        
        int totalPrice = Integer.parseInt(Reservation.duration) * basePrice;
        
        Reservation.basePrice = basePrice;
        Reservation.totalPrice = totalPrice;
        Reservation.roomNo = generateRoomNo();
            
        lblCheckIn.setText(Reservation.checkInDate);
        lblCheckOut.setText(Reservation.checkOutDate);
        lblTotal.setText("PHP " + Integer.toString(totalPrice));
    }
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dateSelection.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        new PaymentProcessing(this).setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnPayActionPerformed

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../assets/Flora_Logo_20x20.png")));
    }
    
    private void setFonts() {
        ReadexProLoader loader = new ReadexProLoader();
        
        readexPro = loader.readexPro(12);
        readexProSemiBold = loader.readexProSemiBold(18);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationConfirmation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCheckIn;
    private javax.swing.JLabel lblCheckOut;
    private javax.swing.JLabel lblConNo;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRoomType;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlBtns;
    private javax.swing.JPanel pnlCheckIn;
    private javax.swing.JPanel pnlCheckOut;
    private javax.swing.JPanel pnlConNo;
    private javax.swing.JPanel pnlDate;
    private javax.swing.JPanel pnlDetails;
    private javax.swing.JPanel pnlEmail;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeadings;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlName;
    private javax.swing.JPanel pnlPrice;
    private javax.swing.JPanel pnlRoom;
    // End of variables declaration//GEN-END:variables
}
