/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import classes.Database;
import java.awt.Font;
import utilities.ReadexProLoader;
import java.awt.Toolkit;

/**
 *
 * @author William
 */
public class Welcome extends javax.swing.JFrame {
    Font readexPro;
    Font readexProSemiBold;
    
    public Welcome() {
        setIconImage();
        setFonts();
        initComponents();
        initDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pnlHeadings = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlBtns = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        pnlCopyright = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flora Macatan");
        setFont(readexPro);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(64, 192, 64, 192));
        mainPanel.setLayout(new java.awt.BorderLayout());

        pnlHeadings.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeadings.setLayout(new java.awt.GridLayout(3, 1));

        logo.setFont(readexProSemiBold);
        logo.setForeground(new java.awt.Color(58, 50, 44));
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("../assets/Logo_Full.png")));
        pnlHeadings.add(logo);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0));
        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jLabel5.setFont(readexPro);
        jLabel5.setForeground(new java.awt.Color(171, 171, 171));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Say goodbye to long wait times and complicated booking");
        jPanel1.add(jLabel5);

        jLabel6.setFont(readexPro);
        jLabel6.setForeground(new java.awt.Color(171, 171, 171));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(" procedures, and reserve your dream stay with ease today!");
        jPanel1.add(jLabel6);

        pnlHeadings.add(jPanel1);

        mainPanel.add(pnlHeadings, java.awt.BorderLayout.NORTH);

        pnlBtns.setBackground(new java.awt.Color(255, 255, 255));
        pnlBtns.setBorder(javax.swing.BorderFactory.createEmptyBorder(32, 1, 32, 1));
        pnlBtns.setLayout(new javax.swing.BoxLayout(pnlBtns, javax.swing.BoxLayout.Y_AXIS));

        btnLogin.setBackground(new java.awt.Color(91, 55, 0));
        btnLogin.setFont(readexPro);
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setAlignmentX(0.5F);
        btnLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 1, 16, 1));
        btnLogin.setBorderPainted(false);
        btnLogin.setFocusPainted(false);
        btnLogin.setMaximumSize(new java.awt.Dimension(350, 48));
        btnLogin.setMinimumSize(new java.awt.Dimension(350, 48));
        btnLogin.setPreferredSize(new java.awt.Dimension(350, 48));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlBtns.add(btnLogin);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(500, 10));
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 10));
        pnlBtns.add(jPanel2);

        btnRegister.setBackground(new java.awt.Color(246, 246, 246));
        btnRegister.setFont(btnLogin.getFont());
        btnRegister.setForeground(new java.awt.Color(58, 50, 44));
        btnRegister.setText("Register");
        btnRegister.setToolTipText("");
        btnRegister.setAlignmentX(0.5F);
        btnRegister.setBorder(btnLogin.getBorder());
        btnRegister.setBorderPainted(false);
        btnRegister.setFocusPainted(false);
        btnRegister.setMaximumSize(new java.awt.Dimension(350, 48));
        btnRegister.setMinimumSize(new java.awt.Dimension(350, 48));
        btnRegister.setPreferredSize(new java.awt.Dimension(350, 48));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        pnlBtns.add(btnRegister);

        mainPanel.add(pnlBtns, java.awt.BorderLayout.CENTER);

        pnlCopyright.setBackground(new java.awt.Color(255, 255, 255));
        pnlCopyright.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(readexPro);
        jLabel3.setForeground(new java.awt.Color(171, 171, 171));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Flora Macatan. Copyright 2023. All Rights Reserved.");
        pnlCopyright.add(jLabel3, java.awt.BorderLayout.CENTER);

        mainPanel.add(pnlCopyright, java.awt.BorderLayout.SOUTH);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        new Register().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        new Login().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void initDb() {
        Database database = new Database();
    }
    
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../assets/Flora_Logo_20x20.png")));
    }
    
    private void setFonts() {
        ReadexProLoader loader = new ReadexProLoader();
        
        readexPro = loader.readexPro(12);
        readexProSemiBold = loader.readexProSemiBold(32);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        }
        catch (Exception e) {
            System.out.println("UIManager Exception : "+e);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pnlBtns;
    private javax.swing.JPanel pnlCopyright;
    private javax.swing.JPanel pnlHeadings;
    // End of variables declaration//GEN-END:variables
}
